// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_links.sql

package store

import (
	"context"
	"database/sql"
)

const countRecentMagicLinksByUserID = `-- name: CountRecentMagicLinksByUserID :one
SELECT COUNT(*) FROM magic_links
WHERE user_id = ?
  AND created_at > datetime('now', '-1 hour')
`

func (q *Queries) CountRecentMagicLinksByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentMagicLinksByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (token, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING token, user_id, created_at, expires_at
`

type CreateMagicLinkParams struct {
	Token     string
	UserID    int64
	ExpiresAt string
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, createMagicLink, arg.Token, arg.UserID, arg.ExpiresAt)
	var i MagicLink
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredMagicLinks = `-- name: DeleteExpiredMagicLinks :execresult
DELETE FROM magic_links WHERE expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredMagicLinks(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredMagicLinks)
}

const deleteMagicLink = `-- name: DeleteMagicLink :exec
DELETE FROM magic_links WHERE token = ?
`

func (q *Queries) DeleteMagicLink(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteMagicLink, token)
	return err
}

const deleteUserMagicLinks = `-- name: DeleteUserMagicLinks :exec
DELETE FROM magic_links WHERE user_id = ?
`

func (q *Queries) DeleteUserMagicLinks(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserMagicLinks, userID)
	return err
}

const getMagicLinkWithUser = `-- name: GetMagicLinkWithUser :one
SELECT
    m.token,
    m.user_id,
    m.created_at,
    m.expires_at,
    u.id,
    u.username,
    u.display_name,
    u.email,
    u.is_admin
FROM magic_links m
JOIN users u ON m.user_id = u.id
WHERE m.token = ?
  AND m.expires_at > datetime('now')
`

type GetMagicLinkWithUserRow struct {
	Token       string
	UserID      int64
	CreatedAt   string
	ExpiresAt   string
	ID          int64
	Username    string
	DisplayName string
	Email       sql.NullString
	IsAdmin     int64
}

func (q *Queries) GetMagicLinkWithUser(ctx context.Context, token string) (GetMagicLinkWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getMagicLinkWithUser, token)
	var i GetMagicLinkWithUserRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.IsAdmin,
	)
	return i, err
}
