// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender_id, recipient_id, content)
VALUES (?, ?, ?)
RETURNING id, sender_id, recipient_id, content, created_at
`

type CreateMessageParams struct {
	SenderID    int64
	RecipientID int64
	Content     string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.SenderID, arg.RecipientID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldMessages = `-- name: DeleteOldMessages :execresult
DELETE FROM messages
WHERE created_at < datetime('now', '-30 days')
`

func (q *Queries) DeleteOldMessages(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldMessages)
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT
    m.id,
    m.sender_id,
    m.recipient_id,
    m.content,
    m.created_at,
    u.display_name AS sender_display_name
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE (m.sender_id = ? AND m.recipient_id = ?)
   OR (m.sender_id = ? AND m.recipient_id = ?)
ORDER BY m.created_at DESC
LIMIT ?
OFFSET ?
`

type GetConversationMessagesParams struct {
	SenderID      int64
	RecipientID   int64
	SenderID_2    int64
	RecipientID_2 int64
	Limit         int64
	Offset        int64
}

type GetConversationMessagesRow struct {
	ID                int64
	SenderID          int64
	RecipientID       int64
	Content           string
	CreatedAt         string
	SenderDisplayName string
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMessages,
		arg.SenderID,
		arg.RecipientID,
		arg.SenderID_2,
		arg.RecipientID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.CreatedAt,
			&i.SenderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMessagePerUser = `-- name: GetRecentMessagePerUser :many
SELECT
    m.id, m.sender_id, m.recipient_id, m.content, m.created_at,
    u.display_name AS other_user_display_name
FROM messages m
JOIN users u ON u.id = CASE
    WHEN m.sender_id = ? THEN m.recipient_id
    ELSE m.sender_id
END
WHERE m.sender_id = ? OR m.recipient_id = ?
ORDER BY m.created_at DESC
`

type GetRecentMessagePerUserParams struct {
	SenderID    int64
	SenderID_2  int64
	RecipientID int64
}

type GetRecentMessagePerUserRow struct {
	ID                   int64
	SenderID             int64
	RecipientID          int64
	Content              string
	CreatedAt            string
	OtherUserDisplayName string
}

func (q *Queries) GetRecentMessagePerUser(ctx context.Context, arg GetRecentMessagePerUserParams) ([]GetRecentMessagePerUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessagePerUser, arg.SenderID, arg.SenderID_2, arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMessagePerUserRow
	for rows.Next() {
		var i GetRecentMessagePerUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.CreatedAt,
			&i.OtherUserDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
