// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Invitation struct {
	Token     string
	Email     string
	InvitedBy int64
	CreatedAt string
	ExpiresAt string
}

type MagicLink struct {
	Token     string
	UserID    int64
	CreatedAt string
	ExpiresAt string
}

type Message struct {
	ID          int64
	SenderID    int64
	RecipientID int64
	Content     string
	CreatedAt   string
}

type Session struct {
	Token     string
	UserID    int64
	CreatedAt string
	ExpiresAt string
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	IsAdmin      int64
	CreatedAt    string
	Email        sql.NullString
}
