// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING token, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execresult
DELETE FROM sessions WHERE expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredSessions)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.token,
    s.user_id,
    s.created_at,
    s.expires_at,
    u.id AS user_id,
    u.username,
    u.display_name,
    u.is_admin
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = ?
  AND s.expires_at > datetime('now')
`

type GetSessionWithUserRow struct {
	Token       string
	UserID      int64
	CreatedAt   string
	ExpiresAt   string
	UserID_2    int64
	Username    string
	DisplayName string
	IsAdmin     int64
}

func (q *Queries) GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, token)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID_2,
		&i.Username,
		&i.DisplayName,
		&i.IsAdmin,
	)
	return i, err
}
